"""RealtorRegistrationNumber — the Maihomme number an approved realtor logs in
with (SCRUM-207).

One LIVE row per realtor, created when an admin approves their application (see
app/services/realtor_registration.py). `deleted_at` NULL = the number still
authenticates; every read path filters on it, so revoking a number is a soft
delete and not a migration.

The number itself is generated by the `realtor_registration_number_seq`
sequence inside the INSERT (see the repository) — Python never picks a value,
so two concurrent issuances cannot collide.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import Uuid

from app.models.user import Base


class RealtorRegistrationNumber(Base):
    __tablename__ = "realtor_registration_numbers"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("users.id"), nullable=False)
    registration_number: Mapped[str] = mapped_column(String(32), nullable=False)
    issued_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
